# configuration for https://github.com/EmbarkStudios/cargo-deny

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unicode-3.0",
    "Zlib",
]
version = 2
confidence-threshold = 0.8

[advisories]
version = 2
yanked = "allow"

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
